spring:
  application:
    name: docker-cloud-producer
  datasource: 
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  liquibase:
    enabled: true
    change-log: "classpath:/db/changelog/db.changelog-master.yaml"
    contexts: dev
  flyway:
    enabled: true
    locations: "classpath:/db/migration"
    baseline-on-migrate: true
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
    pool:
      enabled: true
    
server:
  port: 8001
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7999/eureka/
        
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
