spring:
  application:
    name: docker-cloud-producer
    
server:
  port: 8001
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7999/eureka/
        
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    